### ISSUE TITLE
Support for partials?

### ISSUE THREAD

**Issue by tomarrell** [maciejhirsz/ramhorns#10]
G'day,

Was just giving your library a go and was wondering whether you were considering support for partials? Apologies if this is already possible, have been searching around for something to fill the use case where I need to compose several separate templates.

Cheers

**Comment by maciejhirsz** [comment]
Not possible yet, I've been considering how to do it but haven't settled on anything specific yet. My idea right now is to have it available at preprocessing when loading templates from files. Do you have any specific requirements you'd like to have addressed?

**Comment by tomarrell** [comment]
I'm currently using the functionality provided by https://github.com/sunng87/handlebars-rust#template-inheritance.

I don't have any specific requirements other than just being able to define partial blocks to be composed at runtime. 

I was thinking a basic implementation to begin with would be wrapping template creation in a composition step, with the parser composing the named partial blocks into a single template, and then running the renderer across it. Not sure if there are any limitations that might make this challenging, but happy to help out with an implementation if you have any ideas where you'd like to begin.

**Comment by grego** [comment]
I could try to implement this. Would the way to work @tomarrell described be acceptable?

**Comment by maciejhirsz** [comment]
@grego ye, that sounds like a good idea!

**Comment by maciejhirsz** [comment]
Solved by #16.
