### ISSUE TITLE
Status of ramhorns

### ISSUE THREAD

**Issue by Weasy666** [maciejhirsz/ramhorns#11]
I read that you did this as an experimental template engine, but i like what you did so far. Especially that this template engine is pretty fast and allows hot-reloading of templates at runtime.

So i just wanted to know if you have any plans of continuing this project.

**Comment by maciejhirsz** [comment]
I tend to work in burst, so yes, eventually. Right now I have all I need of it, if you have specific features you'd like to see opening an issue could help.

**Comment by Weasy666** [comment]
Great! Nice to hear that you want to continue.

So with that question answered, i will close this issue.
