### ISSUE TITLE
LGPL license?

### ISSUE THREAD

**Issue by zeerooth** [maciejhirsz/ramhorns#66]
Context: There is a PR for the paperclip crate (https://github.com/paperclip-rs/paperclip/pull/506) that introduces openAPI v3 spec + moustache templates and adds ramhorns as a dependency for processing said templates. However, since ramhorns is under GPL v3 and the paperclip crate is licensed under MIT then merging this would require changing the entire crate's license to GPL v3, which is something that the author (understandably) doesn't want to do. In that case relicensing ramhorns under LGPL v3 would allow it to be included there (while retaining most of the benefits of GPL v3 license)

Is it something that's feasible?

**Comment by maciejhirsz** [comment]
If we are to change the license I'd prefer to go with MPL-2.0 instead of LGPL.

Would all contributors agree changing the license to MPL?

CC: @grego @tiagolobocastro @halvko @MrJohz @creativcoder @htrefil

**Comment by halvko** [comment]
I have no problem with that

/Erik Funder Carstensen ***@***.***)

**Comment by grego** [comment]
I prefer GPL, but I agree if others do.

**Comment by MrJohz** [comment]
I'm okay with this being changed to MPL as well.
